### ISSUE TITLE
Falco CloudWatch Log Format

### ISSUE THREAD

**Issue by lusoal** [aws-samples/aws-securityhub-falco-ecs-eks-integration#1]
I'm using fluent-bit as log exporter in my EKS cluster, and the falco logs are not being right parsed by the Lambda.

**Comment by rajarshidas** [comment]
Hi @lusoal,

In case you are using the Helm chart for falco, then can you please try and set the the `jsonOutput` property in https://github.com/falcosecurity/charts/blob/master/falco/values.yaml is set to `true` explicitly? (default is false when cloned)

Thanks.

**Comment by rajarshidas** [comment]
Hope the previous comment has helped. Closing the issue for now.
